// <auto-generated />
using System;
using Hid.Checkpoint.DataAccess.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hid.Checkpoint.DataAccess.Ef.Migrations
{
    [DbContext(typeof(CheckPointsContext))]
    [Migration("20230405230532_request_author")]
    partial class request_author
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessLevelAccessPoint", b =>
                {
                    b.Property<int>("AccessLevelsId")
                        .HasColumnType("integer")
                        .HasColumnName("access_levels_id");

                    b.Property<int>("AccessPointsId")
                        .HasColumnType("integer")
                        .HasColumnName("access_points_id");

                    b.HasKey("AccessLevelsId", "AccessPointsId")
                        .HasName("pk_access_level_access_point");

                    b.HasIndex("AccessPointsId")
                        .HasDatabaseName("ix_access_level_access_point_access_points_id");

                    b.ToTable("access_level_access_point", (string)null);
                });

            modelBuilder.Entity("ApproveStageApproveStage", b =>
                {
                    b.Property<int>("NextStagesId")
                        .HasColumnType("integer")
                        .HasColumnName("next_stages_id");

                    b.Property<int>("PrevStagesId")
                        .HasColumnType("integer")
                        .HasColumnName("prev_stages_id");

                    b.HasKey("NextStagesId", "PrevStagesId")
                        .HasName("pk_approve_stage_approve_stage");

                    b.HasIndex("PrevStagesId")
                        .HasDatabaseName("ix_approve_stage_approve_stage_prev_stages_id");

                    b.ToTable("approve_stage_approve_stage", (string)null);
                });

            modelBuilder.Entity("DevicePassRequest", b =>
                {
                    b.Property<int>("DevicesId")
                        .HasColumnType("integer")
                        .HasColumnName("devices_id");

                    b.Property<int>("PassRequestsId")
                        .HasColumnType("integer")
                        .HasColumnName("pass_requests_id");

                    b.HasKey("DevicesId", "PassRequestsId")
                        .HasName("pk_device_pass_request");

                    b.HasIndex("PassRequestsId")
                        .HasDatabaseName("ix_device_pass_request_pass_requests_id");

                    b.ToTable("device_pass_request", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("AccessTimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("access_time_from");

                    b.Property<TimeOnly>("AccessTimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("access_time_to");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week");

                    b.Property<int>("GlobalId")
                        .HasColumnType("integer")
                        .HasColumnName("global_id");

                    b.Property<bool>("HolidaysAccess")
                        .HasColumnType("boolean")
                        .HasColumnName("holidays_access");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_access_levels");

                    b.ToTable("access_levels", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.AccessPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("GlobalId")
                        .HasColumnType("integer")
                        .HasColumnName("global_id");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_access_points");

                    b.ToTable("access_points", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ApproveChain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproveState")
                        .HasColumnType("integer")
                        .HasColumnName("approve_state");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("CurrentStageId")
                        .HasColumnType("integer")
                        .HasColumnName("current_stage_id");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<int>("PassRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pass_request_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_approve_chain");

                    b.HasIndex("CurrentStageId")
                        .HasDatabaseName("ix_approve_chain_current_stage_id");

                    b.HasIndex("PassRequestId")
                        .HasDatabaseName("ix_approve_chain_pass_request_id");

                    b.ToTable("approve_chain", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ApproveChainTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_approve_chain_template");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_approve_chain_template_type_id");

                    b.ToTable("approve_chain_template", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ApproveStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproverId")
                        .HasColumnType("integer")
                        .HasColumnName("approver_id");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer")
                        .HasColumnName("chain_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("PassRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pass_request_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_approve_stage");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("ix_approve_stage_approver_id");

                    b.HasIndex("ChainId")
                        .HasDatabaseName("ix_approve_stage_chain_id");

                    b.HasIndex("PassRequestId")
                        .HasDatabaseName("ix_approve_stage_pass_request_id");

                    b.ToTable("approve_stage", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ApproveStageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsMultipleStage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multiple_stage");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_approve_stage_type");

                    b.ToTable("approve_stage_type", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<string>("Iso2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iso2");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iso3");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.CustomizableProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discriminator");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("InterfaceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interface_id");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TypeFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_full_name");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_customizable_property");

                    b.ToTable("customizable_property", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("CustomizableProperty");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cause")
                        .HasColumnType("text")
                        .HasColumnName("cause");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("PassType")
                        .HasColumnType("integer")
                        .HasColumnName("pass_type");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sn");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("ContractDescription")
                        .HasColumnType("text")
                        .HasColumnName("contract_description");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DisbandDate")
                        .HasColumnType("date")
                        .HasColumnName("disband_date");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<string>("Imns")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("imns");

                    b.Property<string>("ImnsName")
                        .HasColumnType("text")
                        .HasColumnName("imns_name");

                    b.Property<string>("Inn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("inn");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<string>("Kpp")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kpp");

                    b.Property<string>("Okato")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("okato");

                    b.Property<string>("Okopf")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("okopf");

                    b.Property<string>("Okpo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("okpo");

                    b.Property<string>("Oktmo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("oktmo");

                    b.Property<string>("Okved")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("okved");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.PassRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Additional")
                        .HasColumnType("text")
                        .HasColumnName("additional");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expired_date");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("request_type_id");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.Property<string>("VisitPurpose")
                        .HasColumnType("text")
                        .HasColumnName("visit_purpose");

                    b.HasKey("Id")
                        .HasName("pk_pass_requests");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_pass_requests_author_id");

                    b.HasIndex("RequestTypeId")
                        .HasDatabaseName("ix_pass_requests_request_type_id");

                    b.ToTable("pass_requests", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.PassRequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<TimeSpan?>("MaxPeriod")
                        .HasColumnType("interval")
                        .HasColumnName("max_period");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_pass_request_type");

                    b.ToTable("pass_request_type", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproveStageId")
                        .HasColumnType("integer")
                        .HasColumnName("approve_stage_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<int?>("PassRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pass_request_id");

                    b.Property<int?>("SubdivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("subdivision_id");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("ApproveStageId")
                        .HasDatabaseName("ix_persons_approve_stage_id");

                    b.HasIndex("PassRequestId")
                        .HasDatabaseName("ix_persons_pass_request_id");

                    b.HasIndex("SubdivisionId")
                        .HasDatabaseName("ix_persons_subdivision_id");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position_title");

                    b.Property<int?>("SubdivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("subdivision_id");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_position");

                    b.HasIndex("SubdivisionId")
                        .HasDatabaseName("ix_position_subdivision_id");

                    b.ToTable("position", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.PropertyMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ColumnDefaultVisibility")
                        .HasColumnType("boolean")
                        .HasColumnName("column_default_visibility");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<string>("PropertyId1")
                        .HasColumnType("text")
                        .HasColumnName("property_id1");

                    b.Property<int?>("RequestTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("request_type_id");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<int?>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean")
                        .HasColumnName("visible");

                    b.Property<string>("discriminator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discriminator");

                    b.HasKey("Id")
                        .HasName("pk_property_metadata");

                    b.HasIndex("PropertyId1")
                        .HasDatabaseName("ix_property_metadata_property_id1");

                    b.HasIndex("RequestTypeId")
                        .HasDatabaseName("ix_property_metadata_request_type_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_property_metadata_user_id");

                    b.ToTable("property_metadata", (string)null);

                    b.HasDiscriminator<string>("discriminator").HasValue("PropertyMetadata");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Subdivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<DateOnly?>("DisbandDate")
                        .HasColumnType("date")
                        .HasColumnName("disband_date");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<string>("Kpp")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kpp");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<string>("Okato")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("okato");

                    b.Property<string>("Okpo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("okpo");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int?>("ParentSubdivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_subdivision_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_subdivision");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_subdivision_manager_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_subdivision_organization_id");

                    b.HasIndex("ParentSubdivisionId")
                        .HasDatabaseName("ix_subdivision_parent_subdivision_id");

                    b.ToTable("subdivision", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccessLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("access_level_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<int?>("RolesValue")
                        .HasColumnType("integer")
                        .HasColumnName("roles_value");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("AccessLevelId")
                        .HasDatabaseName("ix_user_access_level_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_user_employee_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.OrganizationProperty", b =>
                {
                    b.HasBaseType("Hid.Checkpoint.Domain.Models.CustomizableProperty");

                    b.HasDiscriminator().HasValue("OrganizationProperty");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.PersonProperty", b =>
                {
                    b.HasBaseType("Hid.Checkpoint.Domain.Models.CustomizableProperty");

                    b.HasDiscriminator().HasValue("PersonProperty");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ProfileProperty", b =>
                {
                    b.HasBaseType("Hid.Checkpoint.Domain.Models.CustomizableProperty");

                    b.HasDiscriminator().HasValue("ProfileProperty");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.RequestProperty", b =>
                {
                    b.HasBaseType("Hid.Checkpoint.Domain.Models.CustomizableProperty");

                    b.HasDiscriminator().HasValue("RequestProperty");

                    b.HasData(
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.Additional",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Дополнительно",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.Additional",
                            Removed = false,
                            Name = "Additional",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.ApproveChains",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.ApproveChains",
                            Removed = false,
                            Name = "ApproveChains",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.Author",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Автор",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.Author",
                            Removed = false,
                            Name = "Author",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.Created",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Создано",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.Created",
                            Removed = false,
                            Name = "Created",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.Date",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Дата запроса",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.Date",
                            Removed = false,
                            Name = "Date",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.Devices",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Устройства",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.Devices",
                            Removed = false,
                            Name = "Devices",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.ExpiredDate",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Действует до",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.ExpiredDate",
                            Removed = false,
                            Name = "ExpiredDate",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.Guests",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Посетители",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.Guests",
                            Removed = false,
                            Name = "Guests",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.Id",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "ID",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.Id",
                            Removed = false,
                            Name = "Id",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.Removed",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Удалено",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.Removed",
                            Removed = false,
                            Name = "Removed",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.RequestType",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Тип запроса",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.RequestType",
                            Removed = false,
                            Name = "RequestType",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.RequestTypeId",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Id типа запроса",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.RequestTypeId",
                            Removed = false,
                            Name = "RequestTypeId",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.Updated",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Обновлено",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.Updated",
                            Removed = false,
                            Name = "Updated",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "Hid.Checkpoint.Domain.Models.PassRequest.VisitPurpose",
                            Created = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Цель визита",
                            InterfaceId = "Hid.Checkpoint.Domain.Models.PassRequest.VisitPurpose",
                            Removed = false,
                            Name = "VisitPurpose",
                            TypeFullName = "Hid.Checkpoint.Domain.Models.PassRequest",
                            TypeName = "PassRequest",
                            Updated = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.OrganizationMetadata", b =>
                {
                    b.HasBaseType("Hid.Checkpoint.Domain.Models.PropertyMetadata");

                    b.HasDiscriminator().HasValue("OrganizationMetadata");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.PersonMetadata", b =>
                {
                    b.HasBaseType("Hid.Checkpoint.Domain.Models.PropertyMetadata");

                    b.HasDiscriminator().HasValue("PersonMetadata");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ProfileMetadata", b =>
                {
                    b.HasBaseType("Hid.Checkpoint.Domain.Models.PropertyMetadata");

                    b.HasDiscriminator().HasValue("ProfileMetadata");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.RequestMetadata", b =>
                {
                    b.HasBaseType("Hid.Checkpoint.Domain.Models.PropertyMetadata");

                    b.HasDiscriminator().HasValue("RequestMetadata");
                });

            modelBuilder.Entity("AccessLevelAccessPoint", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.AccessLevel", null)
                        .WithMany()
                        .HasForeignKey("AccessLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_level_access_point_access_levels_access_levels_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.AccessPoint", null)
                        .WithMany()
                        .HasForeignKey("AccessPointsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_level_access_point_access_points_access_points_id");
                });

            modelBuilder.Entity("ApproveStageApproveStage", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.ApproveStage", null)
                        .WithMany()
                        .HasForeignKey("NextStagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approve_stage_approve_stage_approve_stage_next_stages_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.ApproveStage", null)
                        .WithMany()
                        .HasForeignKey("PrevStagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approve_stage_approve_stage_approve_stage_prev_stages_id");
                });

            modelBuilder.Entity("DevicePassRequest", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_pass_request_devices_devices_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.PassRequest", null)
                        .WithMany()
                        .HasForeignKey("PassRequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_pass_request_pass_requests_pass_requests_id");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ApproveChain", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.ApproveStage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approve_chain_approve_stage_current_stage_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.PassRequest", "PassRequest")
                        .WithMany("ApproveChains")
                        .HasForeignKey("PassRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approve_chain_pass_requests_pass_request_id");

                    b.Navigation("CurrentStage");

                    b.Navigation("PassRequest");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ApproveChainTemplate", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.PassRequestType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approve_chain_template_pass_request_type_type_id");

                    b.OwnsMany("Hid.Checkpoint.Domain.Models.ApproveStageTemplate", "Stages", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ApproveChainId")
                                .HasColumnType("integer")
                                .HasColumnName("approve_chain_id");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<int>("StageTypeId")
                                .HasColumnType("integer")
                                .HasColumnName("stage_type_id");

                            b1.HasKey("Id")
                                .HasName("pk_approve_stage_template");

                            b1.HasIndex("ApproveChainId")
                                .HasDatabaseName("ix_approve_stage_template_approve_chain_id");

                            b1.HasIndex("StageTypeId")
                                .HasDatabaseName("ix_approve_stage_template_stage_type_id");

                            b1.ToTable("approve_stage_template", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ApproveChainId")
                                .HasConstraintName("fk_approve_stage_template_approve_chain_template_approve_chain_t");

                            b1.HasOne("Hid.Checkpoint.Domain.Models.ApproveStageType", "StageType")
                                .WithMany()
                                .HasForeignKey("StageTypeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_approve_stage_template_approve_stage_type_stage_type_id");

                            b1.Navigation("StageType");
                        });

                    b.Navigation("Stages");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ApproveStage", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.Person", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .HasConstraintName("fk_approve_stage_persons_approver_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.ApproveChain", "Chain")
                        .WithMany("Stages")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approve_stage_approve_chain_approve_chain_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.PassRequest", "PassRequest")
                        .WithMany()
                        .HasForeignKey("PassRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approve_stage_pass_requests_pass_request_id");

                    b.Navigation("Approver");

                    b.Navigation("Chain");

                    b.Navigation("PassRequest");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.PassRequest", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pass_requests_user_author_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.PassRequestType", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pass_requests_pass_request_type_request_type_id");

                    b.Navigation("Author");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Person", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.ApproveStage", null)
                        .WithMany("Responsibles")
                        .HasForeignKey("ApproveStageId")
                        .HasConstraintName("fk_persons_approve_stage_approve_stage_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.PassRequest", null)
                        .WithMany("Guests")
                        .HasForeignKey("PassRequestId")
                        .HasConstraintName("fk_persons_pass_requests_pass_request_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.Subdivision", null)
                        .WithMany("Employees")
                        .HasForeignKey("SubdivisionId")
                        .HasConstraintName("fk_persons_subdivision_subdivision_id");

                    b.OwnsMany("Hid.Checkpoint.Domain.Models.Profile", "Profiles", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Code")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("code");

                            b1.Property<int?>("CountryId")
                                .HasColumnType("integer")
                                .HasColumnName("country_id");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("created");

                            b1.Property<DateOnly?>("DateOfBirth")
                                .HasColumnType("date")
                                .HasColumnName("date_of_birth");

                            b1.Property<DateOnly?>("DisabledDate")
                                .HasColumnType("date")
                                .HasColumnName("disabled_date");

                            b1.Property<DateOnly?>("DismissalDate")
                                .HasColumnType("date")
                                .HasColumnName("dismissal_date");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<DateOnly?>("EmploymentDate")
                                .HasColumnType("date")
                                .HasColumnName("employment_date");

                            b1.Property<Guid?>("ExternalId")
                                .HasColumnType("uuid")
                                .HasColumnName("external_id");

                            b1.Property<Guid?>("ExternalIndividual")
                                .HasColumnType("uuid")
                                .HasColumnName("external_individual");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("first_name");

                            b1.Property<string>("Inn")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("inn");

                            b1.Property<bool>("IsEmployee")
                                .HasColumnType("boolean")
                                .HasColumnName("is_employee");

                            b1.Property<bool>("Removed")
                                .HasColumnType("boolean")
                                .HasColumnName("removed");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("last_name");

                            b1.Property<string>("Okpdtr")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("okpdtr");

                            b1.Property<string>("OkpdtrTitle")
                                .HasColumnType("text")
                                .HasColumnName("okpdtr_title");

                            b1.Property<int>("OrganizationId")
                                .HasColumnType("integer")
                                .HasColumnName("organization_id");

                            b1.Property<string>("Patronymic")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("patronymic");

                            b1.Property<int>("PersonId")
                                .HasColumnType("integer")
                                .HasColumnName("person_id");

                            b1.Property<string>("Phone")
                                .HasColumnType("text")
                                .HasColumnName("phone");

                            b1.Property<string>("PositionCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("position_code");

                            b1.Property<int?>("PositionId")
                                .HasColumnType("integer")
                                .HasColumnName("position_id");

                            b1.Property<string>("TabN")
                                .HasColumnType("text")
                                .HasColumnName("tab_n");

                            b1.Property<DateTime?>("Updated")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("updated");

                            b1.HasKey("Id")
                                .HasName("pk_profile");

                            b1.HasIndex("CountryId")
                                .HasDatabaseName("ix_profile_country_id");

                            b1.HasIndex("OrganizationId")
                                .HasDatabaseName("ix_profile_organization_id");

                            b1.HasIndex("PersonId")
                                .HasDatabaseName("ix_profile_person_id");

                            b1.HasIndex("PositionId")
                                .HasDatabaseName("ix_profile_position_id");

                            b1.HasIndex("Phone", "FirstName", "LastName", "DateOfBirth", "OrganizationId")
                                .IsUnique()
                                .HasDatabaseName("ix_profile_phone_first_name_last_name_date_of_birth_organizati");

                            b1.ToTable("profile", (string)null);

                            b1.HasOne("Hid.Checkpoint.Domain.Models.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_profile_country_country_id");

                            b1.HasOne("Hid.Checkpoint.Domain.Models.Organization", "Organization")
                                .WithMany()
                                .HasForeignKey("OrganizationId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_profile_organizations_organization_id");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_profile_persons_person_id");

                            b1.HasOne("Hid.Checkpoint.Domain.Models.Position", "Position")
                                .WithMany()
                                .HasForeignKey("PositionId")
                                .HasConstraintName("fk_profile_position_position_id");

                            b1.Navigation("Country");

                            b1.Navigation("Organization");

                            b1.Navigation("Position");
                        });

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Position", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.Subdivision", "Subdivision")
                        .WithMany()
                        .HasForeignKey("SubdivisionId")
                        .HasConstraintName("fk_position_subdivision_subdivision_id");

                    b.Navigation("Subdivision");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.PropertyMetadata", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.CustomizableProperty", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId1")
                        .HasConstraintName("fk_property_metadata_customizable_property_property_id1");

                    b.HasOne("Hid.Checkpoint.Domain.Models.PassRequestType", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .HasConstraintName("fk_property_metadata_pass_request_type_request_type_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_property_metadata_user_user_id");

                    b.Navigation("Property");

                    b.Navigation("RequestType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Subdivision", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.Person", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subdivision_persons_manager_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.Organization", "Organization")
                        .WithMany("Subdivisions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subdivision_organizations_organization_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.Subdivision", "ParentSubdivision")
                        .WithMany()
                        .HasForeignKey("ParentSubdivisionId")
                        .HasConstraintName("fk_subdivision_subdivision_parent_subdivision_id");

                    b.Navigation("Manager");

                    b.Navigation("Organization");

                    b.Navigation("ParentSubdivision");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.User", b =>
                {
                    b.HasOne("Hid.Checkpoint.Domain.Models.AccessLevel", null)
                        .WithMany("Approvers")
                        .HasForeignKey("AccessLevelId")
                        .HasConstraintName("fk_user_access_levels_access_level_id");

                    b.HasOne("Hid.Checkpoint.Domain.Models.Person", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_persons_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.AccessLevel", b =>
                {
                    b.Navigation("Approvers");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ApproveChain", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.ApproveStage", b =>
                {
                    b.Navigation("Responsibles");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Organization", b =>
                {
                    b.Navigation("Subdivisions");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.PassRequest", b =>
                {
                    b.Navigation("ApproveChains");

                    b.Navigation("Guests");
                });

            modelBuilder.Entity("Hid.Checkpoint.Domain.Models.Subdivision", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
